;complete
Digest_Bin_110f_objects(BinToDecompile)
{
	global
	Bin := FileOpen(BinToDecompile,"r")
	Bin.Read(4)
	RecordSize := 448
	
	loop, % (Bin.Length  - 4) / RecordSize
	{
		If ( (A_TickCount - StartTime) >= 10 ) OR (a_index=1)
		{
			GuiControl, , Text3, % "Decoding Bins...`n" Module " ( " ModuleNum " / " Binorder.Length() " )" "`nRecord: " a_index "/" ((StrSplit((Bin.Length  - 4)  / RecordSize,"`.")[1])) " ("  StrSplit(a_index/ ((Bin.Length  - 4)  / RecordSize) * 100,"`.")[1] "%)"
			StartTime := A_TickCount
		}
		;Record size: 448
		RecordID := a_index 
		Record := Digest[ModFullName,"Decompile",Module,RecordID] := {}
		Record["Name"] := Bin.Read(64) 
		Record["iPadding16"] := Bin.ReadUInt() 
		Record["iPadding17"] := Bin.ReadUInt() 
		Record["iPadding18"] := Bin.ReadUInt() 
		Record["iPadding19"] := Bin.ReadUInt() 
		Record["iPadding20"] := Bin.ReadUInt() 
		Record["iPadding21"] := Bin.ReadUInt() 
		Record["iPadding22"] := Bin.ReadUInt() 
		Record["iPadding23"] := Bin.ReadUInt() 
		Record["iPadding24"] := Bin.ReadUInt() 
		Record["iPadding25"] := Bin.ReadUInt() 
		Record["iPadding26"] := Bin.ReadUInt() 
		Record["iPadding27"] := Bin.ReadUInt() 
		Record["iPadding28"] := Bin.ReadUInt() 
		Record["iPadding29"] := Bin.ReadUInt() 
		Record["iPadding30"] := Bin.ReadUInt() 
		Record["iPadding31"] := Bin.ReadUInt() 
		Record["iPadding32"] := Bin.ReadUInt() 
		Record["iPadding33"] := Bin.ReadUInt() 
		Record["iPadding34"] := Bin.ReadUInt() 
		Record["iPadding35"] := Bin.ReadUInt() 
		Record["iPadding36"] := Bin.ReadUInt() 
		Record["iPadding37"] := Bin.ReadUInt() 
		Record["iPadding38"] := Bin.ReadUInt() 
		Record["iPadding39"] := Bin.ReadUInt() 
		Record["iPadding40"] := Bin.ReadUInt() 
		Record["iPadding41"] := Bin.ReadUInt() 
		Record["iPadding42"] := Bin.ReadUInt() 
		Record["iPadding43"] := Bin.ReadUInt() 
		Record["iPadding44"] := Bin.ReadUInt() 
		Record["iPadding45"] := Bin.ReadUInt() 
		Record["iPadding46"] := Bin.ReadUInt() 
		Record["iPadding47"] := Bin.ReadUInt() 
		Record["Token"] := Trim(Bin.Read(3))
		Record["SpawnMax"] := Bin.ReadUChar() 
		Record["Selectable0"] := Bin.ReadUChar() 
		Record["Selectable1"] := Bin.ReadUChar() 
		Record["Selectable2"] := Bin.ReadUChar() 
		Record["Selectable3"] := Bin.ReadUChar() 
		Record["Selectable4"] := Bin.ReadUChar() 
		Record["Selectable5"] := Bin.ReadUChar() 
		Record["Selectable6"] := Bin.ReadUChar() 
		Record["Selectable7"] := Bin.ReadUChar() 
		Record["TrapProb"] := Bin.ReadUInt() 
		Record["SizeX"] := Bin.ReadUInt() 
		Record["SizeY"] := Bin.ReadUInt() 
		Record["FrameCnt0"] := Bin.ReadUInt() 
		Record["FrameCnt1"] := Bin.ReadUInt() 
		Record["FrameCnt2"] := Bin.ReadUInt() 
		Record["FrameCnt3"] := Bin.ReadUInt() 
		Record["FrameCnt4"] := Bin.ReadUInt() 
		Record["FrameCnt5"] := Bin.ReadUInt() 
		Record["FrameCnt6"] := Bin.ReadUInt() 
		Record["FrameCnt7"] := Bin.ReadUInt() 
		Record["FrameDelta0"] := Bin.ReadUShort() 
		Record["FrameDelta1"] := Bin.ReadUShort() 
		Record["FrameDelta2"] := Bin.ReadUShort() 
		Record["FrameDelta3"] := Bin.ReadUShort() 
		Record["FrameDelta4"] := Bin.ReadUShort() 
		Record["FrameDelta5"] := Bin.ReadUShort() 
		Record["FrameDelta6"] := Bin.ReadUShort() 
		Record["FrameDelta7"] := Bin.ReadUShort() 
		Record["CycleAnim0"] := Bin.ReadUChar() 
		Record["CycleAnim1"] := Bin.ReadUChar() 
		Record["CycleAnim2"] := Bin.ReadUChar() 
		Record["CycleAnim3"] := Bin.ReadUChar() 
		Record["CycleAnim4"] := Bin.ReadUChar() 
		Record["CycleAnim5"] := Bin.ReadUChar() 
		Record["CycleAnim6"] := Bin.ReadUChar() 
		Record["CycleAnim7"] := Bin.ReadUChar() 
		Record["Lit0"] := Bin.ReadUChar() 
		Record["Lit1"] := Bin.ReadUChar() 
		Record["Lit2"] := Bin.ReadUChar() 
		Record["Lit3"] := Bin.ReadUChar() 
		Record["Lit4"] := Bin.ReadUChar() 
		Record["Lit5"] := Bin.ReadUChar() 
		Record["Lit6"] := Bin.ReadUChar() 
		Record["Lit7"] := Bin.ReadUChar() 
		Record["BlocksLight0"] := Bin.ReadUChar() 
		Record["BlocksLight1"] := Bin.ReadUChar() 
		Record["BlocksLight2"] := Bin.ReadUChar() 
		Record["BlocksLight3"] := Bin.ReadUChar() 
		Record["BlocksLight4"] := Bin.ReadUChar() 
		Record["BlocksLight5"] := Bin.ReadUChar() 
		Record["BlocksLight6"] := Bin.ReadUChar() 
		Record["BlocksLight7"] := Bin.ReadUChar() 
		Record["HasCollision0"] := Bin.ReadUChar() 
		Record["HasCollision1"] := Bin.ReadUChar() 
		Record["HasCollision2"] := Bin.ReadUChar() 
		Record["HasCollision3"] := Bin.ReadUChar() 
		Record["HasCollision4"] := Bin.ReadUChar() 
		Record["HasCollision5"] := Bin.ReadUChar() 
		Record["HasCollision6"] := Bin.ReadUChar() 
		Record["HasCollision7"] := Bin.ReadUChar() 
		Record["IsAttackable0"] := Bin.ReadUChar() 
		Record["Start0"] := Bin.ReadUChar() 
		Record["Start1"] := Bin.ReadUChar() 
		Record["Start2"] := Bin.ReadUChar() 
		Record["Start3"] := Bin.ReadUChar() 
		Record["Start4"] := Bin.ReadUChar() 
		Record["Start5"] := Bin.ReadUChar() 
		Record["Start6"] := Bin.ReadUChar() 
		Record["Start7"] := Bin.ReadUChar() 
		Record["OrderFlag0"] := Bin.ReadUChar() 
		Record["OrderFlag1"] := Bin.ReadUChar() 
		Record["OrderFlag2"] := Bin.ReadUChar() 
		Record["OrderFlag3"] := Bin.ReadUChar() 
		Record["OrderFlag4"] := Bin.ReadUChar() 
		Record["OrderFlag5"] := Bin.ReadUChar() 
		Record["OrderFlag6"] := Bin.ReadUChar() 
		Record["OrderFlag7"] := Bin.ReadUChar() 
		Record["EnvEffect"] := Bin.ReadUChar() 
		Record["IsDoor"] := Bin.ReadUChar() 
		Record["BlocksVis"] := Bin.ReadUChar() 
		Record["Orientation"] := Bin.ReadUChar() 
		Record["PreOperate"] := Bin.ReadUChar() 
		Record["Trans"] := Bin.ReadUChar() 
		Record["Mode0"] := Bin.ReadUChar() 
		Record["Mode1"] := Bin.ReadUChar() 
		Record["Mode2"] := Bin.ReadUChar() 
		Record["Mode3"] := Bin.ReadUChar() 
		Record["Mode4"] := Bin.ReadUChar() 
		Record["Mode5"] := Bin.ReadUChar() 
		Record["Mode6"] := Bin.ReadUChar() 
		Record["Mode7"] := Bin.ReadUChar() 
		Record["iPadding81"] := Bin.ReadUChar() 
		Record["Xoffset"] := Bin.ReadInt() 
		Record["Yoffset"] := Bin.ReadInt() 
		Record["Draw"] := Bin.ReadUChar() 
		Record["HD"] := Bin.ReadUChar() 
		Record["TR"] := Bin.ReadUChar() 
		Record["LG"] := Bin.ReadUChar() 
		Record["RA"] := Bin.ReadUChar() 
		Record["LA"] := Bin.ReadUChar() 
		Record["RH"] := Bin.ReadUChar() 
		Record["LH"] := Bin.ReadUChar() 
		Record["SH"] := Bin.ReadUChar() 
		Record["S1"] := Bin.ReadUChar() 
		Record["S2"] := Bin.ReadUChar() 
		Record["S3"] := Bin.ReadUChar() 
		Record["S4"] := Bin.ReadUChar() 
		Record["S5"] := Bin.ReadUChar() 
		Record["S6"] := Bin.ReadUChar() 
		Record["S7"] := Bin.ReadUChar() 
		Record["S8"] := Bin.ReadUChar() 
		Record["TotalPieces"] := Bin.ReadUChar() 
		Record["Xspace"] := Bin.ReadChar() 
		Record["Yspace"] := Bin.ReadChar() 
		Record["Red"] := Bin.ReadUChar() 
		Record["Green"] := Bin.ReadUChar() 
		Record["Blue"] := Bin.ReadUChar() 
		Record["SubClass"] := Bin.ReadUChar() 
		Record["NameOffset"] := Bin.ReadInt() 
		Record["iPadding91"] := Bin.ReadUChar() 
		Record["MonsterOK"] := Bin.ReadUChar() 
		Record["OperateRange"] := Bin.ReadUChar() 
		Record["ShrineFunction"] := Bin.ReadUChar() 
		Record["Act"] := Bin.ReadUChar() 
		Record["Lockable"] := Bin.ReadUChar() 
		Record["Gore"] := Bin.ReadUChar() 
		Record["Restore"] := Bin.ReadUChar() 
		Record["RestoreVirgins"] := Bin.ReadUChar() 
		Record["Sync"] := Bin.ReadUChar() 
		Record["iPadding93_1"] := Trim(Bin.Read(2))
		Record["Parm0"] := Bin.ReadInt() 
		Record["Parm1"] := Bin.ReadInt() 
		Record["Parm2"] := Bin.ReadInt() 
		Record["Parm3"] := Bin.ReadInt() 
		Record["Parm4"] := Bin.ReadInt() 
		Record["Parm5"] := Bin.ReadInt() 
		Record["Parm6"] := Bin.ReadInt() 
		Record["Parm7"] := Bin.ReadInt() 
		Record["nTgtFX"] := Bin.ReadUChar() 
		Record["nTgtFY"] := Bin.ReadUChar() 
		Record["nTgtBX"] := Bin.ReadUChar() 
		Record["nTgtBY"] := Bin.ReadUChar() 
		Record["Damage"] := Bin.ReadUChar() 
		Record["CollisionSubst"] := Bin.ReadUChar() 
		Record["iPadding103"] := Bin.ReadUShort() 
		Record["Left"] := Bin.ReadInt() 
		Record["Top"] := Bin.ReadInt() 
		Record["Width"] := Bin.ReadInt() 
		Record["Height"] := Bin.ReadInt() 
		Record["Beta"] := Bin.ReadUChar() 
		Record["InitFn"] := Bin.ReadUChar() 
		Record["PopulateFn"] := Bin.ReadUChar() 
		Record["OperateFn"] := Bin.ReadUChar() 
		Record["ClientFn"] := Bin.ReadUChar() 
		Record["Overlay"] := Bin.ReadUChar() 
		Record["BlockMissile"] := Bin.ReadUChar() 
		Record["DrawUnder"] := Bin.ReadUChar() 
		Record["OpenWarp"] := Bin.ReadUInt() 
		Record["AutoMap"] := Bin.ReadUInt()
		
		
		Kill := "iPadding|104,SpawnMax,Selectable|8,TrapProb,SizeX,SizeY,FrameCnt|8,FrameDelta|8,CycleAnim|8,Lit|8,BlocksLight|8,HasCollision|8,IsAttackable0,Start|8,OrderFlag|8,EnvEffect,IsDoor,BlocksVis,Orientation,PreOperate,Trans,Mode|8,Xoffset,Yoffset,Draw,HD,TR,LG,RA,LA,RH,LH,SH,S|9,TotalPieces,Xspace,Yspace,Red,Green,Blue,SubClass,NameOffset,MonsterOK,OperateRange,ShrineFunction,Lockable,Gore,Restore,RestoreVirgins,Sync,iPadding93_1,Parm|8,nTgtFX,nTgtFY,nTgtBX,nTgtBY,Damage,CollisionSubst,Left,Top,Width,Height,Beta,InitFn,PopulateFn,OperateFn,ClientFn,Overlay,BlockMissile,DrawUnder,OpenWarp,AutoMap"
		RecordKill(Record,kill,0,,-1)
		
		InsertQuick("DigestDB","Decompile | " module,Record)		
		
		For k,v in Record
		{
			KeyCounter += 1
			KeySize += StrLen(v)
		}
		
	}
}