	pushDB = 
	(
		CREATE TABLE [Decompile | arena] (
			[ModNum]	INTEGER,
			[RecordID]	INTEGER,
			[Suicide]	INTEGER,
			[PlayerKill]	INTEGER,
			[PlayerKillPercent]	INTEGER,
			[MonsterKill]	INTEGER,
			[PlayerDeath]	INTEGER,
			[PlayerDeathPercent]	INTEGER,
			[MonsterDeath]	INTEGER
		`);
	)
	retObj.push(pushDB)

	pushDB = 
	(
		CREATE TABLE [Decompile | armor] (
			[ModNum]	INTEGER,
			[RecordID]	INTEGER,
			[flippyfile]	STRING (32),
			[invfile]	STRING (32),
			[uniqueinvfile]	STRING (32),
			[setinvfile]	STRING (32),
			[code]	STRING (4),
			[normcode]	STRING (4),
			[ubercode]	STRING (4),
			[ultracode]	STRING (4),
			[alternategfx]	STRING (4),
			[iPadding37]	INTEGER,
			[iPadding38]	INTEGER,
			[iPadding39]	INTEGER,
			[iPadding40]	INTEGER,
			[iPadding41]	INTEGER,
			[iPadding42]	INTEGER,
			[iPadding43]	INTEGER,
			[iPadding44]	INTEGER,
			[iPadding45]	INTEGER,
			[iPadding46]	INTEGER,
			[iPadding47]	INTEGER,
			[iPadding48]	INTEGER,
			[iPadding49]	INTEGER,
			[iPadding50]	INTEGER,
			[minac]	INTEGER,
			[maxac]	INTEGER,
			[gamble cost]	INTEGER,
			[speed]	INTEGER,
			[bitfield1]	INTEGER,
			[cost]	INTEGER,
			[minstack]	INTEGER,
			[maxstack]	INTEGER,
			[iPadding59]	INTEGER,
			[gemoffset]	INTEGER,
			[namestr]	INTEGER,
			[version]	INTEGER,
			[iPadding61]	INTEGER,
			[auto prefix]	INTEGER,
			[missiletype]	INTEGER,
			[rarity]	INTEGER,
			[level]	INTEGER,
			[mindam]	INTEGER,
			[maxdam]	INTEGER,
			[iPadding64]	INTEGER,
			[iPadding65]	INTEGER,
			[StrBonus]	INTEGER,
			[DexBonus]	INTEGER,
			[reqstr]	INTEGER,
			[reqdex]	INTEGER,
			[absorbs]	INTEGER,
			[invwidth]	INTEGER,
			[invheight]	INTEGER,
			[block]	INTEGER,
			[durability]	INTEGER,
			[nodurability]	INTEGER,
			[iPadding69]	INTEGER,
			[component]	INTEGER,
			[rArm]	INTEGER,
			[lArm]	INTEGER,
			[Torso]	INTEGER,
			[Legs]	INTEGER,
			[rSPad]	INTEGER,
			[lSPad]	INTEGER,
			[iPadding71]	INTEGER,
			[useable]	INTEGER,
			[type]	INTEGER,
			[type2]	INTEGER,
			[iPadding72]	INTEGER,
			[dropsound]	INTEGER,
			[usesound]	INTEGER,
			[dropsfxframe]	INTEGER,
			[unique]	INTEGER,
			[quest]	INTEGER,
			[transparent]	INTEGER,
			[transtbl]	INTEGER,
			[iPadding75]	INTEGER,
			[lightradius]	INTEGER,
			[belt]	INTEGER,
			[stackable]	INTEGER,
			[spawnable]	INTEGER,
			[iPadding77]	INTEGER,
			[durwarning]	INTEGER,
			[qntwarning]	INTEGER,
			[hasinv]	INTEGER,
			[gemsockets]	INTEGER,
			[iPadding78]	STRING (3),
			[iPadding79]	STRING (2),
			[gemapplytype]	INTEGER,
			[levelreq]	INTEGER,
			[magic lvl]	INTEGER,
			[Transform]	INTEGER,
			[InvTrans]	INTEGER,
			[compactsave]	INTEGER,
			[SkipName]	INTEGER,
			[nameable]	INTEGER,
			[AkaraMin]	INTEGER,
			[GheedMin]	INTEGER,
			[CharsiMin]	INTEGER,
			[FaraMin]	INTEGER,
			[LysanderMin]	INTEGER,
			[DrognanMin]	INTEGER,
			[HraltiMin]	INTEGER,
			[AlkorMin]	INTEGER,
			[OrmusMin]	INTEGER,
			[ElzixMin]	INTEGER,
			[AshearaMin]	INTEGER,
			[CainMin]	INTEGER,
			[HalbuMin]	INTEGER,
			[JamellaMin]	INTEGER,
			[MalahMin]	INTEGER,
			[LarzukMin]	INTEGER,
			[DrehyaMin]	INTEGER,
			[AkaraMax]	INTEGER,
			[GheedMax]	INTEGER,
			[CharsiMax]	INTEGER,
			[FaraMax]	INTEGER,
			[LysanderMax]	INTEGER,
			[DrognanMax]	INTEGER,
			[HraltiMax]	INTEGER,
			[AlkorMax]	INTEGER,
			[OrmusMax]	INTEGER,
			[ElzixMax]	INTEGER,
			[AshearaMax]	INTEGER,
			[CainMax]	INTEGER,
			[HalbuMax]	INTEGER,
			[JamellaMax]	INTEGER,
			[MalahMax]	INTEGER,
			[LarzukMax]	INTEGER,
			[DrehyaMax]	INTEGER,
			[AkaraMagicMin]	INTEGER,
			[GheedMagicMin]	INTEGER,
			[CharsiMagicMin]	INTEGER,
			[FaraMagicMin]	INTEGER,
			[LysanderMagicMin]	INTEGER,
			[DrognanMagicMin]	INTEGER,
			[HraltiMagicMin]	INTEGER,
			[AlkorMagicMin]	INTEGER,
			[OrmusMagicMin]	INTEGER,
			[ElzixMagicMin]	INTEGER,
			[AshearaMagicMin]	INTEGER,
			[CainMagicMin]	INTEGER,
			[HalbuMagicMin]	INTEGER,
			[JamellaMagicMin]	INTEGER,
			[MalahMagicMin]	INTEGER,
			[LarzukMagicMin]	INTEGER,
			[DrehyaMagicMin]	INTEGER,
			[AkaraMagicMax]	INTEGER,
			[GheedMagicMax]	INTEGER,
			[CharsiMagicMax]	INTEGER,
			[FaraMagicMax]	INTEGER,
			[LysanderMagicMax]	INTEGER,
			[DrognanMagicMax]	INTEGER,
			[HraltiMagicMax]	INTEGER,
			[AlkorMagicMax]	INTEGER,
			[OrmusMagicMax]	INTEGER,
			[ElzixMagicMax]	INTEGER,
			[AshearaMagicMax]	INTEGER,
			[CainMagicMax]	INTEGER,
			[HalbuMagicMax]	INTEGER,
			[JamellaMagicMax]	INTEGER,
			[MalahMagicMax]	INTEGER,
			[LarzukMagicMax]	INTEGER,
			[DrehyaMagicMax]	INTEGER,
			[AkaraMagicLvl]	INTEGER,
			[GheedMagicLvl]	INTEGER,
			[CharsiMagicLvl]	INTEGER,
			[FaraMagicLvl]	INTEGER,
			[LysanderMagicLvl]	INTEGER,
			[DrognanMagicLvl]	INTEGER,
			[HraltiMagicLvl]	INTEGER,
			[AlkorMagicLvl]	INTEGER,
			[OrmusMagicLvl]	INTEGER,
			[ElzixMagicLvl]	INTEGER,
			[AshearaMagicLvl]	INTEGER,
			[CainMagicLvl]	INTEGER,
			[HalbuMagicLvl]	INTEGER,
			[JamellaMagicLvl]	INTEGER,
			[MalahMagicLvl]	INTEGER,
			[LarzukMagicLvl]	INTEGER,
			[DrehyaMagicLvl]	INTEGER,
			[iPadding102]	INTEGER,
			[NightmareUpgrade]	STRING (4),
			[HellUpgrade]	STRING (4),
			[iPadding105]	INTEGER
		`);
	)
	retObj.push(pushDB)

	pushDB = 
	(
		CREATE TABLE [Decompile | monstats2] (
			[ModNum]	INTEGER,
			[RecordID]	INTEGER,
			[Id]	INTEGER,
			[corpseSel]	INTEGER,
			[shiftSel]	INTEGER,
			[noSel]	INTEGER,
			[alSel]	INTEGER,
			[isSel]	INTEGER,
			[noOvly]	INTEGER,
			[noMap]	INTEGER,
			[noGfxHitTest]	INTEGER,
			[noUniqueShift]	INTEGER,
			[Shadow]	INTEGER,
			[critter]	INTEGER,
			[soft]	INTEGER,
			[large]	INTEGER,
			[small]	INTEGER,
			[isAtt]	INTEGER,
			[revive]	INTEGER,
			[unflatDead]	INTEGER,
			[deadCol]	INTEGER,
			[objCol]	INTEGER,
			[inert]	INTEGER,
			[compositeDeath]	INTEGER,
			[SizeX]	INTEGER,
			[SizeY]	INTEGER,
			[spawnCol]	INTEGER,
			[Height]	INTEGER,
			[OverlayHeight]	INTEGER,
			[pixHeight]	INTEGER,
			[MeleeRng]	INTEGER,
			[iPadding3]	INTEGER,
			[BaseW]	STRING (4),
			[HitClass]	INTEGER,
			[HDvNum]	INTEGER,
			[TRvNum]	INTEGER,
			[LGvNum]	INTEGER,
			[RavNum]	INTEGER,
			[LavNum]	INTEGER,
			[RHvNum]	INTEGER,
			[LHvNum]	INTEGER,
			[SHvNum]	INTEGER,
			[S1vNum]	INTEGER,
			[S2vNum]	INTEGER,
			[S3vNum]	INTEGER,
			[S4vNum]	INTEGER,
			[S5vNum]	INTEGER,
			[S6vNum]	INTEGER,
			[S7vNum]	INTEGER,
			[S8vNum]	INTEGER,
			[iPadding9]	INTEGER,
			[HDv]	STRING (12),
			[TRv]	STRING (12),
			[LGv]	STRING (12),
			[Rav]	STRING (12),
			[Lav]	STRING (12),
			[RHv]	STRING (12),
			[LHv]	STRING (12),
			[SHv]	STRING (12),
			[S1v]	STRING (12),
			[S2v]	STRING (12),
			[S3v]	STRING (12),
			[S4v]	STRING (12),
			[S5v]	STRING (12),
			[S6v]	STRING (12),
			[S7v]	STRING (12),
			[S8v]	STRING (12),
			[iPadding57]	INTEGER,
			[mSC]	INTEGER,
			[mBL]	INTEGER,
			[mA2]	INTEGER,
			[mA1]	INTEGER,
			[mGH]	INTEGER,
			[mWL]	INTEGER,
			[mNU]	INTEGER,
			[mDT]	INTEGER,
			[mRN]	INTEGER,
			[mSQ]	INTEGER,
			[mKB]	INTEGER,
			[mDD]	INTEGER,
			[mS4]	INTEGER,
			[mS3]	INTEGER,
			[mS2]	INTEGER,
			[mS1]	INTEGER,
			[TotalPieces]	INTEGER,
			[dDT]	INTEGER,
			[dNU]	INTEGER,
			[dWL]	INTEGER,
			[dGH]	INTEGER,
			[dA1]	INTEGER,
			[dA2]	INTEGER,
			[dBL]	INTEGER,
			[dSC]	INTEGER,
			[dS1]	INTEGER,
			[dS2]	INTEGER,
			[dS3]	INTEGER,
			[dS4]	INTEGER,
			[dDD]	INTEGER,
			[dKB]	INTEGER,
			[dSQ]	INTEGER,
			[dRN]	INTEGER,
			[SCmv]	INTEGER,
			[A2mv]	INTEGER,
			[A1mv]	INTEGER,
			[S4mv]	INTEGER,
			[S3mv]	INTEGER,
			[S2mv]	INTEGER,
			[S1mv]	INTEGER,
			[InfernoLen]	INTEGER,
			[InfernoAnim]	INTEGER,
			[InfernoRollback]	INTEGER,
			[ResurrectMode]	INTEGER,
			[ResurrectSkill]	INTEGER,
			[htTop]	INTEGER,
			[htLeft]	INTEGER,
			[htWidth]	INTEGER,
			[htHeight]	INTEGER,
			[iPadding69]	INTEGER,
			[automapCel]	INTEGER,
			[localBlood]	INTEGER,
			[Bleed]	INTEGER,
			[Light]	INTEGER,
			[light-r]	INTEGER,
			[light-g]	INTEGER,
			[light-b]	INTEGER,
			[Utrans]	INTEGER,
			[Utrans(N)]	INTEGER,
			[Utrans(H)]	INTEGER,
			[acPaddding]	STRING (3),
			[Heart]	STRING (4),
			[BodyPart]	STRING (4),
			[restore]	INTEGER
		`);
	)
	retObj.push(pushDB)

