;complete
Digest_Bin_110f_misc(BinToDecompile)
{
	global
	Bin := FileOpen(BinToDecompile,"r")
	Bin.Read(4)
	RecordSize := 424
	
	loop, % (Bin.Length  - 4) / RecordSize
	{
		If ( (A_TickCount - StartTime) >= 10 ) OR (a_index=1)
		{
			GuiControl, , Text3, % "Decoding Bins...`n" Module " ( " ModuleNum " / " Binorder.Length() " )" "`nRecord: " a_index "/" ((StrSplit((Bin.Length  - 4)  / RecordSize,"`.")[1])) " ("  StrSplit(a_index/ ((Bin.Length  - 4)  / RecordSize) * 100,"`.")[1] "%)"
			StartTime := A_TickCount
		}
		;Record size: 424
		RecordID := a_index 
		Record := Digest[ModFullName,"Decompile",Module,RecordID] := {}
		Record["flippyfile"] := Trim(Bin.Read(32))
		Record["invfile"] := Trim(Bin.Read(32))
		Record["uniqueinvfile"] := Trim(Bin.Read(32)) 
		Record["acPadding"] := Trim(Bin.Read(32))
		Record["code"] := Trim(Bin.Read(4))
		Record["acPad2"] := Trim(Bin.Read(12))
		Record["alternategfx"] := Trim(Bin.Read(4))
		Record["pSpell"] := Bin.ReadUInt() 
		Record["state"] := Bin.ReadUShort() 
		Record["cstate1"] := Bin.ReadUShort() 
		Record["cstate2"] := Bin.ReadUShort() 
		Record["stat1"] := Bin.ReadUShort() 
		Record["stat2"] := Bin.ReadUShort() 
		Record["stat3"] := Bin.ReadUShort() 
		Record["calc1"] := Bin.ReadUInt() 
		Record["calc2"] := Bin.ReadUInt() 
		Record["calc3"] := Bin.ReadUInt() 
		Record["len"] := Bin.ReadUInt() 
		Record["spelldesc"] := Bin.ReadUShort() 
		Record["spelldescstr"] := Bin.ReadUShort() 
		Record["spelldesccalc"] := Bin.ReadUInt() 
		Record["BetterGem"] := Trim(Bin.Read(4))
		Record["acPad6"] := Trim(Bin.Read(8))
		Record["TMogType"] := Trim(Bin.Read(4))
		Record["acPad7"] := Trim(Bin.Read(8))
		Record["gamble cost"] := Bin.ReadUInt() 
		Record["speed"] := Bin.ReadUChar() 
		Record["acPad9"] := Trim(Bin.Read(3))
		Record["bitfield1"] := Bin.ReadUChar() 
		Record["acPad10"] := Trim(Bin.Read(3))
		Record["cost"] := Bin.ReadUInt() 
		Record["minstack"] := Bin.ReadUInt() 
		Record["maxstack"] := Bin.ReadUInt() 
		Record["spawnstack"] := Bin.ReadUInt() 
		Record["gemoffset"] := Bin.ReadUShort() 
		Record["acPad12"] := Trim(Bin.Read(2))
		Record["namestr"] := Bin.ReadUShort() 
		Record["version"] := Bin.ReadUChar() 
		Record["acPad13"] := Trim(Bin.Read(1))
		Record["auto prefix"] := Bin.ReadUShort() 
		Record["missiletype"] := Bin.ReadUChar() 
		Record["bPad"] := Bin.ReadUChar() 
		Record["rarity"] := Bin.ReadUChar() 
		Record["level"] := Bin.ReadUChar() 
		Record["mindam"] := Bin.ReadUChar() 
		Record["maxdam"] := Bin.ReadUChar() 
		Record["acPad14"] := Trim(Bin.Read(15))
		Record["invwidth"] := Bin.ReadUChar() 
		Record["invheight"] := Bin.ReadUChar() 
		Record["acPad15"] := Trim(Bin.Read(2))
		Record["nodurability"] := Bin.ReadUChar() 
		Record["bPad2"] := Bin.ReadUChar() 
		Record["component"] := Bin.ReadUChar() 
		Record["acPad16"] := Trim(Bin.Read(7))
		Record["useable"] := Bin.ReadUChar() 
		Record["type"] := Bin.ReadUShort() 
		Record["type2"] := Bin.ReadUShort() 
		Record["acPad17"] := Trim(Bin.Read(2))
		Record["dropsound"] := Bin.ReadUShort() 
		Record["usesound"] := Bin.ReadUShort() 
		Record["dropsfxframe"] := Bin.ReadUChar() 
		Record["unique"] := Bin.ReadUChar() 
		Record["quest"] := Bin.ReadUChar() 
		Record["questdiffcheck"] := Bin.ReadUChar() 
		Record["transparent"] := Bin.ReadUChar() 
		Record["transtbl"] := Bin.ReadUChar() 
		Record["bPad4"] := Bin.ReadUChar() 
		Record["lightradius"] := Bin.ReadUChar() 
		Record["belt"] := Bin.ReadUChar() 
		Record["autobelt"] := Bin.ReadUChar() 
		Record["stackable"] := Bin.ReadUChar() 
		Record["spawnable"] := Bin.ReadUChar() 
		Record["spellicon"] := Bin.ReadChar() 
		Record["durwarning"] := Bin.ReadUChar() 
		Record["qntwarning"] := Bin.ReadUChar() 
		Record["hasinv"] := Bin.ReadUChar() 
		Record["gemsockets"] := Bin.ReadUChar() 
		Record["Transmogrify"] := Bin.ReadUChar() 
		Record["TMogMin"] := Bin.ReadUChar() 
		Record["TMogMax"] := Bin.ReadUChar() 
		Record["acPad18"] := Trim(Bin.Read(2))
		Record["gemapplytype"] := Bin.ReadUChar() 
		Record["levelreq"] := Bin.ReadUChar() 
		Record["bPad5"] := Bin.ReadUChar() 
		Record["Transform"] := Bin.ReadUChar() 
		Record["InvTrans"] := Bin.ReadUChar() 
		Record["compactsave"] := Bin.ReadUChar() 
		Record["SkipName"] := Bin.ReadUChar() 
		Record["Nameable"] := Bin.ReadUChar() 
		Record["AkaraMin"] := Bin.ReadUChar() 
		Record["GheedMin"] := Bin.ReadUChar() 
		Record["CharsiMin"] := Bin.ReadUChar() 
		Record["FaraMin"] := Bin.ReadUChar() 
		Record["LysanderMin"] := Bin.ReadUChar() 
		Record["DrognanMin"] := Bin.ReadUChar() 
		Record["HraltiMin"] := Bin.ReadUChar() 
		Record["AlkorMin"] := Bin.ReadUChar() 
		Record["OrmusMin"] := Bin.ReadUChar() 
		Record["ElzixMin"] := Bin.ReadUChar() 
		Record["AshearaMin"] := Bin.ReadUChar() 
		Record["CainMin"] := Bin.ReadUChar() 
		Record["HalbuMin"] := Bin.ReadUChar() 
		Record["JamellaMin"] := Bin.ReadUChar() 
		Record["MalahMin"] := Bin.ReadUChar() 
		Record["LarzukMin"] := Bin.ReadUChar() 
		Record["DrehyaMin"] := Bin.ReadUChar() 
		Record["AkaraMax"] := Bin.ReadUChar() 
		Record["GheedMax"] := Bin.ReadUChar() 
		Record["CharsiMax"] := Bin.ReadUChar() 
		Record["FaraMax"] := Bin.ReadUChar() 
		Record["LysanderMax"] := Bin.ReadUChar() 
		Record["DrognanMax"] := Bin.ReadUChar() 
		Record["HraltiMax"] := Bin.ReadUChar() 
		Record["AlkorMax"] := Bin.ReadUChar() 
		Record["OrmusMax"] := Bin.ReadUChar() 
		Record["ElzixMax"] := Bin.ReadUChar() 
		Record["AshearaMax"] := Bin.ReadUChar() 
		Record["CainMax"] := Bin.ReadUChar() 
		Record["HalbuMax"] := Bin.ReadUChar() 
		Record["JamellaMax"] := Bin.ReadUChar() 
		Record["MalahMax"] := Bin.ReadUChar() 
		Record["LarzukMax"] := Bin.ReadUChar() 
		Record["DrehyaMax"] := Bin.ReadUChar() 
		Record["AkaraMagicMin"] := Bin.ReadUChar() 
		Record["GheedMagicMin"] := Bin.ReadUChar() 
		Record["CharsiMagicMin"] := Bin.ReadUChar() 
		Record["FaraMagicMin"] := Bin.ReadUChar() 
		Record["LysanderMagicMin"] := Bin.ReadUChar() 
		Record["DrognanMagicMin"] := Bin.ReadUChar() 
		Record["HraltiMagicMin"] := Bin.ReadUChar() 
		Record["AlkorMagicMin"] := Bin.ReadUChar() 
		Record["OrmusMagicMin"] := Bin.ReadUChar() 
		Record["ElzixMagicMin"] := Bin.ReadUChar() 
		Record["AshearaMagicMin"] := Bin.ReadUChar() 
		Record["CainMagicMin"] := Bin.ReadUChar() 
		Record["HalbuMagicMin"] := Bin.ReadUChar() 
		Record["JamellaMagicMin"] := Bin.ReadUChar() 
		Record["MalahMagicMin"] := Bin.ReadUChar() 
		Record["LarzukMagicMin"] := Bin.ReadUChar() 
		Record["DrehyaMagicMin"] := Bin.ReadUChar() 
		Record["AkaraMagicMax"] := Bin.ReadUChar() 
		Record["GheedMagicMax"] := Bin.ReadUChar() 
		Record["CharsiMagicMax"] := Bin.ReadUChar() 
		Record["FaraMagicMax"] := Bin.ReadUChar() 
		Record["LysanderMagicMax"] := Bin.ReadUChar() 
		Record["DrognanMagicMax"] := Bin.ReadUChar() 
		Record["HraltiMagicMax"] := Bin.ReadUChar() 
		Record["AlkorMagicMax"] := Bin.ReadUChar() 
		Record["OrmusMagicMax"] := Bin.ReadUChar() 
		Record["ElzixMagicMax"] := Bin.ReadUChar() 
		Record["AshearaMagicMax"] := Bin.ReadUChar() 
		Record["CainMagicMax"] := Bin.ReadUChar() 
		Record["HalbuMagicMax"] := Bin.ReadUChar() 
		Record["JamellaMagicMax"] := Bin.ReadUChar() 
		Record["MalahMagicMax"] := Bin.ReadUChar() 
		Record["LarzukMagicMax"] := Bin.ReadUChar() 
		Record["DrehyaMagicMax"] := Bin.ReadUChar() 
		Record["AkaraMagicLvl"] := Bin.ReadUChar() 
		Record["GheedMagicLvl"] := Bin.ReadUChar() 
		Record["CharsiMagicLvl"] := Bin.ReadUChar() 
		Record["FaraMagicLvl"] := Bin.ReadUChar() 
		Record["LysanderMagicLvl"] := Bin.ReadUChar() 
		Record["DrognanMagicLvl"] := Bin.ReadUChar() 
		Record["HraltiMagicLvl"] := Bin.ReadUChar() 
		Record["AlkorMagicLvl"] := Bin.ReadUChar() 
		Record["OrmusMagicLvl"] := Bin.ReadUChar() 
		Record["ElzixMagicLvl"] := Bin.ReadUChar() 
		Record["AshearaMagicLvl"] := Bin.ReadUChar() 
		Record["CainMagicLvl"] := Bin.ReadUChar() 
		Record["HalbuMagicLvl"] := Bin.ReadUChar() 
		Record["JamellaMagicLvl"] := Bin.ReadUChar() 
		Record["MalahMagicLvl"] := Bin.ReadUChar() 
		Record["LarzukMagicLvl"] := Bin.ReadUChar() 
		Record["DrehyaMagicLvl"] := Bin.ReadUChar() 
		Record["bPad6"] := Bin.ReadUChar() 
		Record["NightmareUpgrade"] := Trim(Bin.Read(4))
		Record["HellUpgrade"] := Trim(Bin.Read(4))
		Record["PermStoreItem"] := Bin.ReadUChar() 
		Record["multibuy"] := Bin.ReadUChar() 
		Record["acPad20"] := Trim(Bin.Read(2))
		
		
		For Index, NPC in ["Cain","Fara","Akara","Alkor","Elzix","Gheed","Halbu","Malah","Ormus"
			,"Charsi","Dreyha","Hralti","Larzuk","Asheara","Drognan","Jamella","Lysander"]
		{
			Kill := NPC "Min,"
				. NPC "Max,"
				. NPC "MagicMin,"
				. NPC "MagicMax"
			RecordKill(Record,Kill,0)
			
			Kill := NPC "MagicLvl"
			RecordKill(Record,Kill,255)			
		}
		
		Kill=stat|3,cstate|2
		RecordKill(Record,Kill,65535)
		
		Kill=calc|3,len,spelldesccalc
		RecordKill(Record,Kill,4294967295)
		
		Kill=acPadding,acPad|20,bPad|6
		RecordKill(Record,Kill,"")
		
		
		InsertQuick("DigestDB","Decompile | " module,Record)		
		
		For k,v in Record
		{
			KeyCounter += 1
			KeySize += StrLen(v)
		}
		
	}
}