;complete
Digest_Bin_110f_levels(BinToDecompile)
{
	global
	Bin := FileOpen(BinToDecompile,"r")
	Bin.Read(4)
	RecordSize := 544
	
	loop, % (Bin.Length  - 4) / RecordSize
	{
		If ( (A_TickCount - StartTime) >= 10 ) OR (a_index=1)
		{
			GuiControl, , Text3, % "Decoding Bins...`n" Module " ( " ModuleNum " / " Binorder.Length() " )" "`nRecord: " a_index "/" ((StrSplit((Bin.Length  - 4)  / RecordSize,"`.")[1])) " ("  StrSplit(a_index/ ((Bin.Length  - 4)  / RecordSize) * 100,"`.")[1] "%)"
			StartTime := A_TickCount
		}
		;Record size: 544
		RecordID := a_index 
		Record := Digest[ModFullName,"Decompile",Module,RecordID] := {}
		Record["Id"] := Bin.ReadUShort() 
		Record["Pal"] := Bin.ReadUChar() 
		Record["Act"] := Bin.ReadUChar() 
		Record["Teleport"] := Bin.ReadUChar() 
		Record["Rain"] := Bin.ReadUChar() 
		Record["Mud"] := Bin.ReadUChar() 
		Record["NoPer"] := Bin.ReadUChar() 
		Record["IsInside"] := Bin.ReadUChar() 
		Record["DrawEdges"] := Bin.ReadUChar() 
		Record["iPadding2"] := Bin.ReadUShort() 
		Record["WarpDist"] := Bin.ReadUInt() 
		Record["MonLvl1"] := Bin.ReadUShort() 
		Record["MonLvl2"] := Bin.ReadUShort() 
		Record["MonLvl3"] := Bin.ReadUShort() 
		Record["MonLvl1Ex"] := Bin.ReadUShort() 
		Record["MonLvl2Ex"] := Bin.ReadUShort() 
		Record["MonLvl3Ex"] := Bin.ReadUShort() 
		Record["MonDen"] := Bin.ReadUInt() 
		Record["MonDen(N)"] := Bin.ReadUInt() 
		Record["MonDen(H)"] := Bin.ReadUInt() 
		Record["MonUMin"] := Bin.ReadUChar() 
		Record["MonUMin(N)"] := Bin.ReadUChar() 
		Record["MonUMin(H)"] := Bin.ReadUChar() 
		Record["MonUMax"] := Bin.ReadUChar() 
		Record["MonUMax(N)"] := Bin.ReadUChar() 
		Record["MonUMax(H)"] := Bin.ReadUChar() 
		Record["MonWndr"] := Bin.ReadUChar() 
		Record["MonSpcWalk"] := Bin.ReadUChar() 
		Record["Quest"] := Bin.ReadUChar() 
		Record["rangedspawn"] := Bin.ReadUChar() 
		Record["NumMon"] := Bin.ReadUShort() 
		Record["iPadding13"] := Bin.ReadUShort() 
		Record["mon1"] := Bin.ReadUShort() 
		Record["mon2"] := Bin.ReadUShort() 
		Record["mon3"] := Bin.ReadUShort() 
		Record["mon4"] := Bin.ReadUShort() 
		Record["mon5"] := Bin.ReadUShort() 
		Record["mon6"] := Bin.ReadUShort() 
		Record["mon7"] := Bin.ReadUShort() 
		Record["mon8"] := Bin.ReadUShort() 
		Record["mon9"] := Bin.ReadUShort() 
		Record["mon10"] := Bin.ReadUShort() 
		Record["mon11"] := Bin.ReadUShort() 
		Record["mon12"] := Bin.ReadUShort() 
		Record["mon13"] := Bin.ReadUShort() 
		Record["mon14"] := Bin.ReadUShort() 
		Record["mon15"] := Bin.ReadUShort() 
		Record["mon16"] := Bin.ReadUShort() 
		Record["mon17"] := Bin.ReadUShort() 
		Record["mon18"] := Bin.ReadUShort() 
		Record["mon19"] := Bin.ReadUShort() 
		Record["mon20"] := Bin.ReadUShort() 
		Record["mon21"] := Bin.ReadUShort() 
		Record["mon22"] := Bin.ReadUShort() 
		Record["mon23"] := Bin.ReadUShort() 
		Record["mon24"] := Bin.ReadUShort() 
		Record["mon25"] := Bin.ReadUShort() 
		Record["nmon1"] := Bin.ReadUShort() 
		Record["nmon2"] := Bin.ReadUShort() 
		Record["nmon3"] := Bin.ReadUShort() 
		Record["nmon4"] := Bin.ReadUShort() 
		Record["nmon5"] := Bin.ReadUShort() 
		Record["nmon6"] := Bin.ReadUShort() 
		Record["nmon7"] := Bin.ReadUShort() 
		Record["nmon8"] := Bin.ReadUShort() 
		Record["nmon9"] := Bin.ReadUShort() 
		Record["nmon10"] := Bin.ReadUShort() 
		Record["nmon11"] := Bin.ReadUShort() 
		Record["nmon12"] := Bin.ReadUShort() 
		Record["nmon13"] := Bin.ReadUShort() 
		Record["nmon14"] := Bin.ReadUShort() 
		Record["nmon15"] := Bin.ReadUShort() 
		Record["nmon16"] := Bin.ReadUShort() 
		Record["nmon17"] := Bin.ReadUShort() 
		Record["nmon18"] := Bin.ReadUShort() 
		Record["nmon19"] := Bin.ReadUShort() 
		Record["nmon20"] := Bin.ReadUShort() 
		Record["nmon21"] := Bin.ReadUShort() 
		Record["nmon22"] := Bin.ReadUShort() 
		Record["nmon23"] := Bin.ReadUShort() 
		Record["nmon24"] := Bin.ReadUShort() 
		Record["nmon25"] := Bin.ReadUShort() 
		Record["umon1"] := Bin.ReadUShort() 
		Record["umon2"] := Bin.ReadUShort() 
		Record["umon3"] := Bin.ReadUShort() 
		Record["umon4"] := Bin.ReadUShort() 
		Record["umon5"] := Bin.ReadUShort() 
		Record["umon6"] := Bin.ReadUShort() 
		Record["umon7"] := Bin.ReadUShort() 
		Record["umon8"] := Bin.ReadUShort() 
		Record["umon9"] := Bin.ReadUShort() 
		Record["umon10"] := Bin.ReadUShort() 
		Record["umon11"] := Bin.ReadUShort() 
		Record["umon12"] := Bin.ReadUShort() 
		Record["umon13"] := Bin.ReadUShort() 
		Record["umon14"] := Bin.ReadUShort() 
		Record["umon15"] := Bin.ReadUShort() 
		Record["umon16"] := Bin.ReadUShort() 
		Record["umon17"] := Bin.ReadUShort() 
		Record["umon18"] := Bin.ReadUShort() 
		Record["umon19"] := Bin.ReadUShort() 
		Record["umon20"] := Bin.ReadUShort() 
		Record["umon21"] := Bin.ReadUShort() 
		Record["umon22"] := Bin.ReadUShort() 
		Record["umon23"] := Bin.ReadUShort() 
		Record["umon24"] := Bin.ReadUShort() 
		Record["umon25"] := Bin.ReadUShort() 
		Record["cmon1"] := Bin.ReadUShort() 
		Record["cmon2"] := Bin.ReadUShort() 
		Record["cmon3"] := Bin.ReadUShort() 
		Record["cmon4"] := Bin.ReadUShort() 
		Record["cpct1"] := Bin.ReadUShort() 
		Record["cpct2"] := Bin.ReadUShort() 
		Record["cpct3"] := Bin.ReadUShort() 
		Record["cpct4"] := Bin.ReadUShort() 
		Record["camt4"] := Bin.ReadUShort() 
		Record["iPadding55"] := Bin.ReadUShort() 
		Record["iPadding56"] := Bin.ReadUInt() 
		Record["Waypoint"] := Bin.ReadUChar() 
		Record["ObjGrp0"] := Bin.ReadUChar() 
		Record["ObjGrp1"] := Bin.ReadUChar() 
		Record["ObjGrp2"] := Bin.ReadUChar() 
		Record["ObjGrp3"] := Bin.ReadUChar() 
		Record["ObjGrp4"] := Bin.ReadUChar() 
		Record["ObjGrp5"] := Bin.ReadUChar() 
		Record["ObjGrp6"] := Bin.ReadUChar() 
		Record["ObjGrp7"] := Bin.ReadUChar() 
		Record["ObjPrb0"] := Bin.ReadUChar() 
		Record["ObjPrb1"] := Bin.ReadUChar() 
		Record["ObjPrb2"] := Bin.ReadUChar() 
		Record["ObjPrb3"] := Bin.ReadUChar() 
		Record["ObjPrb4"] := Bin.ReadUChar() 
		Record["ObjPrb5"] := Bin.ReadUChar() 
		Record["ObjPrb6"] := Bin.ReadUChar() 
		Record["ObjPrb7"] := Bin.ReadUChar() 
		Record["LevelName"] := Trim(Bin.Read(40))
		Record["LevelWarp"] := Trim(Bin.Read(40))
		Record["EntryFile"] := Trim(Bin.Read(39))
		;~ Bin.Read(164)
		Record["iPadding91"] := Bin.ReadUInt() 
		Record["iPadding92"] := Bin.ReadUInt() 
		Record["iPadding93"] := Bin.ReadUInt() 
		Record["iPadding94"] := Bin.ReadUInt() 
		Record["iPadding95"] := Bin.ReadUInt() 
		Record["iPadding96"] := Bin.ReadUInt() 
		Record["iPadding97"] := Bin.ReadUInt() 
		Record["iPadding98"] := Bin.ReadUInt() 
		Record["iPadding99"] := Bin.ReadUInt() 
		Record["iPadding100"] := Bin.ReadUInt() 
		Record["iPadding101"] := Bin.ReadUInt() 
		Record["iPadding102"] := Bin.ReadUInt() 
		Record["iPadding103"] := Bin.ReadUInt() 
		Record["iPadding104"] := Bin.ReadUInt() 
		Record["iPadding105"] := Bin.ReadUInt() 
		Record["iPadding106"] := Bin.ReadUInt() 
		Record["iPadding107"] := Bin.ReadUInt() 
		Record["iPadding108"] := Bin.ReadUInt() 
		Record["iPadding109"] := Bin.ReadUInt() 
		Record["iPadding110"] := Bin.ReadUInt() 
		Record["iPadding111"] := Bin.ReadUInt() 
		Record["iPadding112"] := Bin.ReadUInt() 
		Record["iPadding113"] := Bin.ReadUInt() 
		Record["iPadding114"] := Bin.ReadUInt() 
		Record["iPadding115"] := Bin.ReadUInt() 
		Record["iPadding116"] := Bin.ReadUInt() 
		Record["iPadding117"] := Bin.ReadUInt() 
		Record["iPadding118"] := Bin.ReadUInt() 
		Record["iPadding119"] := Bin.ReadUInt() 
		Record["iPadding120"] := Bin.ReadUInt() 
		Record["iPadding121"] := Bin.ReadUInt() 
		Record["iPadding122"] := Bin.ReadUInt() 
		Record["iPadding123"] := Bin.ReadUInt() 
		Record["iPadding124"] := Bin.ReadUInt() 
		Record["iPadding125"] := Bin.ReadUInt() 
		Record["iPadding126"] := Bin.ReadUInt() 
		Record["iPadding127"] := Bin.ReadUInt() 
		Record["iPadding128"] := Bin.ReadUInt() 
		Record["iPadding129"] := Bin.ReadUInt() 
		Record["iPadding130"] := Bin.ReadUInt() 
		Record["iPadding131"] := Bin.ReadUInt() 
		Record["Themes"] := Bin.ReadUInt() 
		Record["FloorFilter"] := Bin.ReadUInt() 
		Record["BlankScreen"] := Bin.ReadUInt() 
		Record["SoundEnv"] := Bin.ReadUInt()
		
		
		kill=mon|25,nmon|25,umon|25,cmon|4
		RecordKill(Record,Kill,65535)
		
		kill=iPadding|131,cpct|4m,camt4
		RecordKill(Record,Kill,0)
		
		kill=ObjGrp|8,ObjPrb
		RecordKill(Record,Kill,0,,-1)
		
		
		InsertQuick("DigestDB","Decompile | " module,Record)		
		
		For k,v in Record
		{
			KeyCounter += 1
			KeySize += StrLen(v)
		}
		
	}
}